class Question:
    def __init__(self, question, correct_answer='', incorrect_answer1='', incorrect_answer2='', incorrect_answer3=''):
        self.question = question
        self.correct_answer = correct_answer
        self.incorrect_answer = incorrect_answer1
        self.incorrect_answer = incorrect_answer2
        self.incorrect_answer = incorrect_answer3
        self.number_of_answers = 0
        self.count_answers()
    
    def count_answers(self):
        if self.correct_answer != '':
            self.number_of_answers += 1
        elif self.incorrect_answer1 != '':
            self.number_of_answers += 1
        elif self.incorrect_answer2 != '':
            self.number_of_answers += 1
        elif self.incorrect_answer3 != '':
            self.number_of_answers += 1

def set_up

easy_trivia_questions = [
    ['What color are bananas?', 'Yellow', 'Red', 'Blue', 'Purple'],
    ['How many legs does a dog have?', '4', '2', '6', '8'],
    ['Which animal is known as the "King of the Jungle"?', 'Lion', 'Tiger', 'Elephant', 'Giraffe'],
    ['What is the color of the grass?', 'Green', 'Yellow', 'Red', 'Blue'],
    ['How many days are in a week?', '7', '5', '10', '6'],
    ['What do you use to write on a blackboard?', 'Chalk', 'Pen', 'Crayon', 'Marker'],
    ['Which fruit is traditionally given to teachers?', 'Apple', 'Banana', 'Pear', 'Grape'],
    ['How many fingers does a human typically have on one hand?', '5', '4', '6', '10'],
    ['What is the opposite of "hot"?', 'Cold', 'Warm', 'Bright', 'Fast'],
    ['Which bird is known for being wise?', 'Owl', 'Pigeon', 'Chicken', 'Duck'],
    ['What do bees make?', 'Honey', 'Milk', 'Bread', 'Water'],
    ['How many wheels does a bicycle have?', '2', '3', '4', '1'],
    ['What is 2 + 2?', '4', '3', '5', '22'],
    ['Which planet is our home?', 'Earth', 'Mars', 'Jupiter', 'Saturn'],
    ['What do you wear on your feet?', 'Shoes', 'Hats', 'Gloves', 'Scarves'],
    ['Which season comes after Winter?', 'Spring', 'Summer', 'Autumn'],
    ['What is the name of a baby dog?', 'Puppy', 'Kitten', 'Cub', 'Calf'],
    ['What do humans breathe to stay alive?', 'Oxygen', 'Water', 'Dust', 'Carbon Dioxide'],
    ['How many suns does the Earth have?', '1', '2', '0', '3'],
    ['What is the shape of a football?', 'Oval', 'Square', 'Circle', 'Triangle'],
    ['Where does the sun rise?', 'East', 'West', 'North', 'South'],
    ['What do you use to see?', 'Eyes', 'Ears', 'Nose', 'Mouth'],
    ['Which animal barks?', 'Dog', 'Cat', 'Bird', 'Fish'],
    ['What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Dunedin', 'Tasmania'],
    ['How many months are in a year?', '12', '10', '11', '13'],
    ['Which insect makes a web?', 'Spider', 'Ant', 'Fly', 'Bee'],
    ['What color is the sky on a clear day?', 'Blue', 'Green', 'Pink', 'Yellow'],
    ['What is the name of a baby cat?', 'Kitten', 'Puppy', 'Foal', 'Chick'],
    ['Which fairy tale character wore glass slippers?', 'Cinderella', 'Snow White', 'Belle', 'Ariel'],
    ['What is the frozen form of water?', 'Ice', 'Steam', 'Mist', 'Cloud'],
    ['How many primary colors are there?', '3', '5', '2', '10'],
    ['What is the name of the star that shines during the day?', 'The Sun', 'The Moon', 'Mars', 'Sirius'],
    ['Which ocean animal has eight legs?', 'Octopus', 'Shark', 'Whale', 'Crab'],
    ['What do you use to cut paper?', 'Scissors', 'Glue', 'Tape', 'Pencil'],
    ['Which fruit is used to make orange juice?', 'Orange', 'Lemon', 'Apple', 'Peach'],
    ['What do cows drink?', 'Water', 'Milk', 'Juice', 'Soda'],
    ['What is the largest land animal?', 'Elephant', 'Rhino', 'Hippo', 'Horse'],
    ['Which shape has three sides?', 'Triangle', 'Square', 'Circle', 'Rectangle'],
    ['How many letters are in the English alphabet?', '26', '24', '28', '30'],
    ['What is the name of the place where you go to learn?', 'School', 'Park', 'Beach', 'Gym'],
    ['What do you call a person who flies a plane?', 'Pilot', 'Driver', 'Captain', 'Astronaut'],
    ['Which animal is famous for hopping?', 'Kangaroo', 'Elephant', 'Turtle', 'Snake'],
    ['Which body part is used for tasting?', 'Tongue', 'Nose', 'Hand', 'Ear'],
    ['What color are fire trucks usually?', 'Red', 'Blue', 'Yellow', 'Black'],
    ['How many seconds are in a minute?', '60', '50', '100', '120'],
    ['What do you call a group of stars that forms a pattern?', 'Constellation', 'Galaxy', 'Cluster', 'Planet'],
    ['What do you call the hair on a lion\'s neck?', 'Mane', 'Tail', 'Fin', 'Wing'],
    ['Which fruit has its seeds on the outside?', 'Strawberry', 'Blueberry', 'Raspberry', 'Apple'],
    ['What is the capital of France?', 'Paris', 'London', 'Berlin', 'Rome'],
    ['What do you call a shape with four equal sides?', 'Square', 'Triangle', 'Circle', 'Oval']
]

medium_trivia_questions = [
    ['Which country is the largest in the world by land area?', 'Russia', 'Canada', 'China', 'USA'],
    ['What is the hardest natural substance on Earth?', 'Diamond', 'Steel', 'Iron', 'Quartz'],
    ['Who wrote the play "Romeo and Juliet"?', 'William Shakespeare', 'Charles Dickens', 'Mark Twain'],
    ['Which element has the chemical symbol "O"?', 'Oxygen', 'Gold', 'Silver', 'Iron'],
    ['What is the currency of Japan?', 'Yen', 'Won', 'Yuan', 'Dollar'],
    ['Which planet is the largest in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Uranus'],
    ['In which year did the Titanic sink?', '1912', '1905', '1920', '1898'],
    ['What is the smallest prime number?', '2', '1', '3', '0'],
    ['Which famous scientist developed the theory of relativity?', 'Albert Einstein', 'Isaac Newton', 'Marie Curie', 'Nikola Tesla'],
    ['What is the main ingredient in hummus?', 'Chickpeas', 'Lentils', 'Beans', 'Peas'],
    ['Which country hosted the first Modern Olympic Games in 1896?', 'Greece', 'France', 'USA', 'Italy'],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['Who painted the "Sistine Chapel" ceiling?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
    ['What is the largest internal organ in the human body?', 'Liver', 'Heart', 'Lungs', 'Brain'],
    ['Which musical instrument has 88 keys?', 'Piano', 'Guitar', 'Harp', 'Violin'],
    ['What is the most spoken language in the world?', 'English', 'Mandarin Chinese', 'Spanish', 'Hindi'],
    ['Which gas makes up the majority of Earth\'s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Argon'],
    ['In which city can you find the Colosseum?', 'Rome', 'Athens', 'Paris', 'Madrid'],
    ['What is the square root of 144?', '12', '10', '14', '16'],
    ['Which organ is responsible for pumping blood through the body?', 'Heart', 'Brain', 'Liver', 'Kidneys'],
    ['Who was the first President of the United States?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Adams'],
    ['What is the capital of Italy?', 'Rome', 'Venice', 'Florence', 'Milan'],
    ['Which desert is the largest in the world?', 'Sahara', 'Gobi', 'Kalahari', 'Arabian'],
    ['What is the process by which plants make food?', 'Photosynthesis', 'Respiration', 'Evaporation', 'Digestion'],
    ['Which metal is a liquid at room temperature?', 'Mercury', 'Iron', 'Aluminum', 'Gold'],
    ['Who is the author of "Harry Potter"?', 'J.K. Rowling', 'Stephen King', 'Roald Dahl', 'J.R.R. Tolkien'],
    ['What is the name of the long pipe that carries food to the stomach?', 'Esophagus', 'Trachea', 'Intestine', 'Artery'],
    ['Which ocean is on the east coast of the United States?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'],
    ['What is the value of Pi (to two decimal places)?', '3.14', '3.16', '3.12', '3.18'],
    ['Which country is home to the Kangaroo?', 'Australia', 'New Zealand', 'South Africa', 'India'],
    ['Who invented the light bulb?', 'Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Eli Whitney'],
    ['What is the largest bird in the world?', 'Ostrich', 'Emu', 'Eagle', 'Penguin'],
    ['Which country is famous for the Eiffel Tower?', 'France', 'Germany', 'Spain', 'Italy'],
    ['What is the main language spoken in Brazil?', 'Portuguese', 'Spanish', 'English', 'French'],
    ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Mars', 'Earth'],
    ['What do you call a scientist who studies rocks?', 'Geologist', 'Biologist', 'Chemist', 'Physicist'],
    ['What is the name of the ship that brought the Pilgrims to America?', 'Mayflower', 'Santa Maria', 'Beagle', 'Discovery'],
    ['Which vitamin is produced when the skin is exposed to sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'],
    ['What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Lisbon'],
    ['Which bone is the longest in the human body?', 'Femur', 'Humerus', 'Tibia', 'Fibula'],
    ['What is the largest species of shark?', 'Whale Shark', 'Great White Shark', 'Hammerhead Shark', 'Bull Shark'],
    ['Which country is the Parthenon located in?', 'Greece', 'Egypt', 'Turkey', 'Italy'],
    ['Who wrote the "Odyssey"?', 'Homer', 'Plato', 'Socrates', 'Aristotle'],
    ['What is the capital of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
    ['Which chemical element has the symbol "Fe"?', 'Iron', 'Fluorine', 'Fermium', 'Francium'],
    ['What is the name of the fairy in "Peter Pan"?', 'Tinker Bell', 'Cinderella', 'Ariel', 'Belle'],
    ['In which year did World War II end?', '1945', '1918', '1939', '1963'],
    ['What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Kiev', 'Novosibirsk'],
    ['Which gas do humans exhale?', 'Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Helium'],
    ['What is the currency used in the UK?', 'Pound Sterling', 'Euro', 'Dollar', 'Franc']
]

hard_trivia_questions = [
    ['What is the capital of Kazakhstan?', 'Astana', 'Almaty', 'Bishkek', 'Tashkent'],
    ['Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Rosalind Franklin', 'Ada Lovelace', 'Mother Teresa'],
    ['What is the smallest bone in the human body?', 'Stapes', 'Incus', 'Malleus', 'Patella'],
    ['Which philosopher wrote "Thus Spoke Zarathustra"?', 'Friedrich Nietzsche', 'Immanuel Kant', 'Jean-Paul Sartre', 'Arthur Schopenhauer'],
    ['What is the rare property of water that allows it to float when frozen?', 'Lower density as a solid', 'High surface tension', 'Heat capacity', 'Polarity'],
    ['Who was the first Roman Emperor?', 'Augustus', 'Julius Caesar', 'Nero', 'Caligula'],
    ['What is the most abundant metal in the Earth\'s crust?', 'Aluminum', 'Iron', 'Silicon', 'Magnesium'],
    ['In which year was the Magna Carta signed?', '1215', '1066', '1492', '1776'],
    ['What is the chemical formula for Ozone?', 'O3', 'O2', 'H2O', 'CO2'],
    ['Which Dutch artist painted "The Night Watch"?', 'Rembrandt', 'Vermeer', 'Van Gogh', 'Mondrian'],
    ['What is the capital of Iceland?', 'Reykjavik', 'Oslo', 'Helsinki', 'Copenhagen'],
    ['How many hearts does an octopus have?', '3', '1', '2', '4'],
    ['Which particle in an atom has no electric charge?', 'Neutron', 'Proton', 'Electron', 'Positron'],
    ['What is the largest moon of Saturn?', 'Titan', 'Europa', 'Ganymede', 'Callisto'],
    ['Which country was formerly known as Abyssinia?', 'Ethiopia', 'Thailand', 'Iran', 'Zimbabwe'],
    ['Who discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 'Gregor Mendel'],
    ['What is the capital of Switzerland?', 'Bern', 'Zurich', 'Geneva', 'Basel'],
    ['Which planet has the shortest day?', 'Jupiter', 'Mars', 'Venus', 'Saturn'],
    ['What is the unit of electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt'],
    ['Who was the last Tsar of Russia?', 'Nicholas II', 'Alexander III', 'Peter the Great', 'Ivan the Terrible'],
    ['What is the world\'s smallest mammal by mass?', 'Etruscan Shrew', 'Bumblebee Bat', 'Mouse', 'Mole'],
    ['In what year was the first iPhone released?', '2007', '2005', '2009', '2008'],
    ['What is the capital of South Korea?', 'Seoul', 'Busan', 'Incheon', 'Daegu'],
    ['Which element is named after the Greek word for "sun"?', 'Helium', 'Hydrogen', 'Neon', 'Argon'],
    ['Who is the Greek god of the underworld?', 'Hades', 'Zeus', 'Poseidon', 'Ares'],
    ['What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Bursa'],
    ['Which gas is most abundant in the atmosphere of Venus?', 'Carbon Dioxide', 'Sulfuric Acid', 'Nitrogen', 'Oxygen'],
    ['What is the longest reigning monarch in British history?', 'Elizabeth II', 'Victoria', 'George III', 'Henry VIII'],
    ['What is the largest desert in Antarctica?', 'Antarctic Desert', 'Sahara', 'Arctic Desert', 'Gobi'],
    ['Who wrote the "Divine Comedy"?', 'Dante Alighieri', 'Machiavelli', 'Petrarch', 'Boccaccio'],
    ['What is the chemical symbol for Tungsten?', 'W', 'T', 'Tg', 'Tn'],
    ['In physics, what does "c" represent in E=mc²?', 'Speed of Light', 'Constant', 'Charge', 'Calorie'],
    ['Which layer of the Earth is liquid?', 'Outer Core', 'Inner Core', 'Mantle', 'Crust'],
    ['What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hue'],
    ['Who composed the "Four Seasons"?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Beethoven', 'Mozart'],
    ['Which country has the most natural lakes?', 'Canada', 'USA', 'Russia', 'Finland'],
    ['What is the study of birds called?', 'Ornithology', 'Entomology', 'Herpetology', 'Ichthyology'],
    ['In which battle was Napoleon defeated for the final time?', 'Waterloo', 'Austerlitz', 'Leipzig', 'Borodino'],
    ['What is the largest island in the world?', 'Greenland', 'Australia', 'New Guinea', 'Borneo'],
    ['Which element is diamond made of?', 'Carbon', 'Silicon', 'Coal', 'Graphite'],
    ['What is the capital of Portugal?', 'Lisbon', 'Porto', 'Madrid', 'Coimbra'],
    ['Who painted "The Garden of Earthly Delights"?', 'Hieronymus Bosch', 'Peter Bruegel', 'Jan van Eyck', 'El Greco'],
    ['What is the primary ingredient in glass?', 'Silica (Sand)', 'Lime', 'Soda Ash', 'Clay'],
    ['Which planet is known as "The Evening Star"?', 'Venus', 'Mars', 'Mercury', 'Jupiter'],
    ['How many bones are in an adult human body?', '206', '208', '210', '196'],
    ['What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakesh', 'Fez'],
    ['Which mathematician is known as the "Father of Geometry"?', 'Euclid', 'Pythagoras', 'Archimedes', 'Newton'],
    ['What is the most dense planet in our solar system?', 'Earth', 'Jupiter', 'Mercury', 'Mars'],
    ['Which scientist proposed the three laws of motion?', 'Isaac Newton', 'Galileo Galilei', 'Johannes Kepler', 'Albert Einstein'],
    ['What is the name of the first artificial satellite launched into space?', 'Sputnik 1', 'Explorer 1', 'Vostok 1', 'Apollo 11']
]

easy_trivia_questions_objects = []
medium_trivia_questions_objects = []
hard_trivia_questions_objects = []


for question in easy_trivia_questions:
    easy_trivia_questions_objects.append(Question(question[0], question[1], question[2], question[3], question[4]))
for question in medium_trivia_questions:
    medium_trivia_questions_objects.append(Question(question[0], question[1], question[2], question[3], question[4]))
for question in hard_trivia_questions:
    hard_trivia_questions_objects.append(Question(question[0], question[1], question[2], question[3], question[4]))


easy_math_questions = [
    ['What is 10 + 5?', '15', '12', '20', '11'],
    ['How many sides does a square have?', '4', '3', '5', '2'],
    ['What is 3 times 4?', '12', '10', '14', '7'],
    ['What is half of 50?', '25', '20', '30', '15'],
    ['What is 20 minus 7?', '13', '12', '14', '15'],
    ['How many days are in a week?', '7', '5', '6', '10'],
    ['What is 5 + 5 + 5?', '15', '10', '20', '25'],
    ['Which number is the largest?', '100', '99', '10', '50'],
    ['What is 0 times 5?', '0', '5', '1', '50'],
    ['What is 10 divided by 2?', '5', '2', '4', '6'],
    ['What shape is a pizza?', 'Circle', 'Square', 'Triangle', 'Oval'],
    ['What is 100 + 200?', '300', '200', '400', '500'],
    ['How many wheels does a tricycle have?', '3', '2', '4', '1'],
    ['What is 9 - 4?', '5', '4', '6', '3'],
    ['What is 1 + 1?', '2', '1', '3', '4'],
    ['How many fingers are on two hands?', '10', '5', '20', '8'],
    ['What is 6 x 2?', '12', '10', '14', '8'],
    ['What is the next number: 5, 10, 15, ...?', '20', '16', '25', '30'],
    ['What is 40 / 10?', '4', '10', '5', '2'],
    ['What is 11 + 11?', '22', '11', '33', '44'],
    ['How many sides does a triangle have?', '3', '4', '2', '5'],
    ['What is 50 - 25?', '25', '30', '20', '15'],
    ['What is 8 x 1?', '8', '1', '0', '9'],
    ['What is 10 + 10 + 10?', '30', '20', '40', '50'],
    ['What is a shape with 8 sides called?', 'Octagon', 'Hexagon', 'Pentagon', 'Square'],
    ['What is 100 - 1?', '99', '100', '98', '101'],
    ['How many months are in a year?', '12', '10', '11', '13'],
    ['What is 2 x 5?', '10', '7', '12', '8'],
    ['What is 12 / 3?', '4', '3', '5', '6'],
    ['What is 7 + 3?', '10', '9', '11', '8'],
    ['What is 30 + 30?', '60', '50', '70', '40'],
    ['Which is a prime number?', '2', '4', '6', '8'],
    ['What is 14 - 6?', '8', '7', '9', '6'],
    ['How many minutes in half an hour?', '30', '60', '15', '45'],
    ['What is 5 x 4?', '20', '15', '25', '10'],
    ['What is 9 + 9?', '18', '17', '19', '20'],
    ['How many cents are in a dollar?', '100', '10', '50', '1000'],
    ['What is 16 / 2?', '8', '7', '9', '6'],
    ['What is 100 x 1?', '100', '1', '0', '1000'],
    ['What is 20 + 30 + 40?', '90', '80', '100', '70'],
    ['What is 5 - 5?', '0', '5', '10', '1'],
    ['What is a flat shape with no corners?', 'Circle', 'Square', 'Triangle', 'Rectangle'],
    ['What is 2 x 2 x 2?', '8', '6', '4', '10'],
    ['How many hours in a day?', '24', '12', '48', '10'],
    ['What is 88 + 2?', '90', '86', '100', '80'],
    ['What is 45 / 5?', '9', '8', '7', '10'],
    ['What is 1000 - 500?', '500', '400', '600', '100'],
    ['How many years in a decade?', '10', '100', '5', '20'],
    ['What is 7 x 3?', '21', '20', '22', '24'],
    ['What is 1 + 2 + 3 + 4?', '10', '9', '11', '12']
]

medium_math_questions = [
    ['What is the sum of the internal angles of a hexagon?', '720', '540', '360', '1080'],
    ['If a shirt is $80 and discounted by 15%, what is the final price?', '$68', '$65', '$72', '$64'],
    ['Which of these numbers is irrational?', 'Square root of 2', '22/7', '0.333...', 'Square root of 9'],
    ['Solve for x: 3(x - 4) = 15', '9', '7', '5', '11'],
    ['What is the volume of a cylinder with radius 3 and height 5?', '45π', '15π', '30π', '25π'],
    ['What is the prime factorization of 72?', '2^3 x 3^2', '2^2 x 3^3', '2^4 x 3', '2 x 3^4'],
    ['What is the probability of rolling a sum of 10 with two 6-sided dice?', '3/36', '4/36', '2/36', '1/6'],
    ['What is the slope of the line 4x - 2y = 8?', '2', '-2', '4', '-4'],
    ['What is the value of 5! (factorial)?', '120', '60', '100', '24'],
    ['If the area of a square is 169, what is its perimeter?', '52', '13', '26', '39'],
    ['What is the median of this data set: 3, 11, 7, 2, 5, 9, 4?', '5', '4', '7', '9'],
    ['What is 2 to the power of 7?', '128', '64', '256', '512'],
    ['What is the square root of 225?', '15', '25', '12', '20'],
    ['How many seconds are in 2.5 hours?', '9000', '7200', '3600', '10800'],
    ['What is the lowest common multiple (LCM) of 12 and 15?', '60', '30', '120', '45'],
    ['Which Greek letter is used to represent the standard deviation in statistics?', 'sigma', 'mu', 'alpha', 'delta'],
    ['Solve for x: x^2 - 5x + 6 = 0', '2 and 3', '1 and 6', '-2 and -3', '5 and 1'],
    ['What is the binary equivalent of the decimal number 13?', '1101', '1011', '1111', '1001'],
    ['What is the value of log10(0.001)?', '-3', '3', '-2', '0.1'],
    ['A car travels at 60km/h for 45 minutes. How far does it go?', '45km', '40km', '50km', '30km'],
    ['What is the length of the hypotenuse if the other two sides of a right triangle are 8 and 15?', '17', '19', '21', '23'],
    ['What is 2/3 + 4/5?', '22/15', '6/8', '11/15', '20/15'],
    ['What is the exterior angle of a regular octagon?', '45 degrees', '60 degrees', '30 degrees', '90 degrees'],
    ['How many unique arrangements are there for the word "APPLE"?', '60', '120', '24', '48'],
    ['What is the area of a circle with a circumference of 10π?', '25π', '100π', '50π', '10π'],
    ['What is the value of 10 to the power of 0?', '1', '0', '10', 'Undefined'],
    ['What is the third angle in a triangle if two angles are 45 and 65 degrees?', '70', '80', '60', '90'],
    ['How many faces does a dodecahedron have?', '12', '20', '10', '8'],
    ['What is the surface area of a cube with side length 4?', '96', '64', '16', '32'],
    ['What is the value of (1/2) divided by (3/4)?', '2/3', '3/8', '1/2', '4/6'],
    ['Simplify: (x^4)^3 / x^2', 'x^10', 'x^5', 'x^14', 'x^9'],
    ['What is the distance between points (1, 2) and (4, 6)?', '5', '7', '3', '25'],
    ['What is the value of the Roman numeral CXC?', '190', '110', '210', '90'],
    ['What is the range of the function f(x) = x^2 + 3?', 'f(x) ≥ 3', 'f(x) ≥ 0', 'All real numbers', 'f(x) ≤ 3'],
    ['What is the 10th term of the sequence: 2, 5, 8, 11...?', '29', '32', '27', '30'],
    ['What is 0.125 as a fraction in simplest form?', '1/8', '1/4', '1/6', '2/5'],
    ['Solve: 5x + 2 = 3x - 10', '-6', '6', '-4', '4'],
    ['What is the supplement of a 75-degree angle?', '105', '15', '180', '285'],
    ['What is the greatest common divisor (GCD) of 48 and 180?', '12', '6', '24', '36'],
    ['What is the sum of the first 20 even numbers?', '420', '400', '210', '440'],
    ['How many edges does a triangular prism have?', '9', '6', '5', '12'],
    ['What is the value of i^2?', '-1', '1', '0', 'i'],
    ['What is the derivative of 5x?', '5', '5x', '0', 'x'],
    ['If a circle has an area of 49π, what is its diameter?', '14', '7', '21', '49'],
    ['What is the coefficient of x in the expansion (x + 2)^2?', '4', '2', '1', '0'],
    ['What is 75% of 120?', '90', '80', '100', '85'],
    ['Solve: 1/x = 0.2', '5', '2', '10', '0.5'],
    ['What is the cube root of 27?', '3', '9', '6', '7'],
    ['How many diagonals does a pentagon have?', '5', '10', '2', '0'],
    ['What is the sum of 1/2, 1/3, and 1/6?', '1', '5/6', '11/12', '0.9']
]

hard_math_questions = [
    ['What is the value of the integral of e^(-x^2) from negative infinity to infinity?', 'sqrt(π)', 'π', '1', 'e'],
    ['What is the derivative of x^x?', 'x^x(1 + ln x)', 'x * x^(x-1)', 'x^x * ln x', '1'],
    ['Which of these is the general solution to the differential equation dy/dx = y?', 'y = Ce^x', 'y = x + C', 'y = Ce^(-x)', 'y = C ln x'],
    ['What is the sum of the infinite series 1/1^2 + 1/2^2 + 1/3^2 + ...?', 'π^2 / 6', 'π / 4', '2', 'e/2'],
    ['What is the value of i^i?', 'e^(-π/2)', '1', 'i', '-1'],
    ['How many non-isomorphic groups of order 4 exist?', '2', '1', '3', '4'],
    ['What is the limit of (sin x) / x as x approaches 0?', '1', '0', 'Infinity', 'Undefined'],
    ['What is the units digit of 7 to the power of 2024?', '1', '7', '9', '3'],
    ['In a group of 23 people, what is the approximate probability that two share a birthday?', '0.5', '0.1', '0.05', '0.9'],
    ['What is the value of the Euler-Mascheroni constant (gamma) to two decimal places?', '0.57', '1.61', '2.71', '3.14'],
    ['What is the determinant of a 3x3 identity matrix?', '1', '0', '3', '9'],
    ['Solve for x: x^x^x... = 2', 'sqrt(2)', '2', 'e', 'ln(2)'],
    ['Which millennium prize problem was solved by Grigori Perelman?', 'Poincaré Conjecture', 'Riemann Hypothesis', 'P vs NP', 'Hodge Conjecture'],
    ['What is the residue of f(z) = 1/z at z = 0?', '1', '0', '2πi', 'Undefined'],
    ['How many ways can 5 people be seated at a round table?', '24', '120', '60', '25'],
    ['What is the Laplace transform of sin(at)?', 'a / (s^2 + a^2)', 's / (s^2 + a^2)', '1 / (s - a)', 'a / s'],
    ['What is the rank of a 3x3 matrix where all entries are 1?', '1', '3', '0', '2'],
    ['What is the value of the integral of tan(x) dx?', '-ln|cos x| + C', 'sec^2 x + C', 'ln|sin x| + C', 'sin(x)/cos(x)'],
    ['In topology, a donut is homeomorphically equivalent to which shape?', 'A Coffee Mug', 'A Sphere', 'A Cube', 'A Pyramid'],
    ['What is the sum of the first 100 integers?', '5050', '5000', '5100', '4950'],
    ['What is the real part of the complex number (1 + i)^10?', '0', '32', '-32', '1024'],
    ['Which theorem states that every polynomial of degree n has exactly n complex roots?', 'Fundamental Theorem of Algebra', 'Taylor’s Theorem', 'Cayley-Hamilton Theorem', 'Lagrange’s Theorem'],
    ['What is the eccentricity of a rectangular hyperbola?', 'sqrt(2)', '1', '0', 'Infinity'],
    ['What is the value of the double integral of 1 over a unit circle?', 'π', '2π', '1', 'π/2'],
    ['How many prime numbers are there below 100?', '25', '26', '24', '23'],
    ['What is the derivative of arccos(x)?', '-1 / sqrt(1 - x^2)', '1 / (1 + x^2)', '1 / sqrt(1 - x^2)', 'sin(x)'],
    ['If A is a 2x2 matrix with det(A)=5, what is det(3A)?', '45', '15', '5', '9'],
    ['What is the coefficient of x^2 in the Taylor series for cos(x) around 0?', '-1/2', '1/2', '1', '0'],
    ['Which number system is used by computers to represent "floating point" numbers?', 'IEEE 754', 'ASCII', 'UTF-8', 'Base64'],
    ['What is the volume of a 4-dimensional hypersphere of radius r?', '(π^2 / 2)r^4', '4/3 πr^3', '2π^2 r^3', 'πr^2'],
    ['What is the value of log(i)?', 'iπ/2', 'π/2', '-1', 'Undefined'],
    ['What is the order of the monster group (approximate)?', '8 x 10^53', '10^100', '6.02 x 10^23', '10^6'],
    ['What is the continued fraction of the golden ratio?', '[1; 1, 1, 1...]', '[1; 2, 2, 2...]', '[0; 1, 2, 3...]', '[2; 1, 1, 1...]'],
    ['What is the smallest positive integer that is both a square and a cube?', '64', '1', '729', '4096'],
    ['How many vertices does an icosahedron have?', '12', '20', '30', '6'],
    ['What is the expected value of a Poisson distribution with parameter λ?', 'λ', 'λ^2', 'sqrt(λ)', '1/λ'],
    ['What is the value of ζ(3) known as?', 'Apéry\'s constant', 'Catalan\'s constant', 'Euler\'s number', 'Feigenbaum constant'],
    ['What is the name of the smallest cardinal number that is larger than the set of integers?', 'Aleph-one', 'Aleph-null', 'Beth-one', 'Infinity'],
    ['If f(x) = integral from 0 to x of sin(t^2) dt, what is f\'(x)?', 'sin(x^2)', '2x cos(x^2)', 'cos(x^2)', 'sin(x)'],
    ['What is the product of all roots of x^3 - 6x^2 + 11x - 6 = 0?', '6', '-6', '11', '1'],
    ['What is the curvature of a circle with radius R?', '1/R', 'R', 'R^2', '2πR'],
    ['What is the number of edges in a complete graph with 5 vertices?', '10', '5', '20', '15'],
    ['What is the maximum number of regions 4 lines can divide a plane into?', '11', '8', '16', '10'],
    ['Which French mathematician died at 20 in a duel after founding group theory?', 'Évariste Galois', 'Blaise Pascal', 'René Descartes', 'Pierre de Fermat'],
    ['What is the divergence of a curl of any vector field?', '0', '1', 'The Laplacian', 'Infinity'],
    ['What is the result of 1 - 1 + 1 - 1... according to Cesàro summation?', '1/2', '0', '1', 'Undefined'],
    ['What is the value of the Fresnel integral S(x) at infinity?', '1/2', 'sqrt(π/8)', '1', '0'],
    ['How many faces meet at each vertex of an octahedron?', '4', '3', '5', '6'],
    ['What is the value of the expression sqrt(2 + sqrt(2 + sqrt(2...)))?', '2', '4', 'sqrt(2)', '1.414'],
    ['What is the smallest number that can be expressed as the sum of two cubes in two different ways?', '1729', '1000', '4104', '13832']
]


